### ISSUE TITLE
Failures when simulator is in non-portrait orientation

### ISSUE THREAD

**Issue by ohammersmith** [terriblelabs/motion-juxtapose#20]
If I rotate the device before taking a screenshot, I get this sort of error:

```
  - looks like demo screen [ERROR: NameError - uninitialized constant Juxtapose::MacBaconStrategy::M_PI_2]

NameError: uninitialized constant Juxtapose::MacBaconStrategy::M_PI_2
    mac_bacon_strategy.rb:47:in `save_current:': DemoScreen - looks like demo screen
    screenshotter.rb:117:in `verify'
    screenshotter.rb:107:in `attempt_verify:'
    screenshotter.rb:23:in `looks_like?:'
    screenshotter.rb:27:in `it_should_look_like:'
    spec.rb:459:in `execute_block'
    spec.rb:421:in `run_postponed_block:’
```

The issue is that the constants for π set in `screens hotter.rb` aren't picked up over in `mac_bacon_strategy.rb`.

I have a fix and will create a PR/patch shortly.

**Comment by squidpunch** [comment]
fixed via #21
